const Resume = {
  header: {
    name: 'Vikash Singh',
    email: 'vik625singh@gmail.com',
    phone: '775-998-0143',
    github: 'https://github.com/vik625',
    linkedin: 'https://linkedin.com/in/vik625',
    address: 'VIP Colony, Chaklokman, Dalsinghsarai',
    website: 'https://vik625.github.io/',
    city: 'Samastipur',
    state: 'Bihar',
    zip: '848114',
    country: 'India',
  },
  experience: [
    {
      company: 'Newton School',
      city: 'Bengaluru',
      state: 'Karnataka',
      position: 'Newton School Coding Boot Camp',
      dateFrom: '04/2020',
      dateTo: '09/2020',
      primaryWorkBrief: 'Full Stack Web Development along with Problem Solving.',
      impact1: '',
      impact2: 'Technical Stack learned: Node JS, React JS, Express JS, Mongo DB, HTML, CSS, JavaScript, and Bootstrap.',
      impact3: 'Participated in various Coding contest organized by the platform.',
      impact4: 'Worked on various projects like To-do, Quiz App.',
      isVisible: true,
    },
    {
      company: 'Aspire vision Tech Education Pvt. Ltd',
      city: 'Hyderabad',
      state: 'Telangana',
      position: 'BlockChain Developer and Trainee',
      dateFrom: '05/2018',
      dateTo: 'PRESENT',
      primaryWorkBrief: 'Developing blockchain software and decentrallized application.',
      impact1: 'Introduce students to the concepts of Blockchain and its platforms – Bitcoin, Ethereum, Hyperledger and MultiChain.',
      impact2: 'My course provides an overview of the structure and mechanism of Blockchain.',
      impact3: '',
      impact4: '',
      isVisible: true,
    },
    {
      company: 'StaTwig-Hyderabad',
      city: 'Hyderabad',
      state: 'Telangana',
      position: 'BlockChain Engineer',
      dateFrom: '05/2018',
      dateTo: '05/2019',
      primaryWorkBrief: 'Brief description of your main tasks.',
      impact1: 'TechnologyStack: Blockchain, IPFS, Solidity, Azure’s private blockchain, Rinkeby Test Net, Ethereum, MetaMask, web3, React/Redux, Node.js, HTML, CSS',
      impact2: '',
      impact3: 'Functions: Tracking and tracing of various supply chain events with alert mechanism using IOT sensors.',
      impact4: 'Development of REST APIs(Node/Express) forvarious get/post request to filter user inputs.',
      isVisible: true,
    },
  ],
  education: [
    {
      site: 'IIIT Guwahati',
      dateFrom: '2016',
      dateTo: '2020',
      studyDegree: 'B-Tech, 7.83 CGPA',
      isVisible: true,
    },
    {
      site: 'Vidyapati +2 Mow Bazidpur (North)',
      dateFrom: '2013',
      dateTo: '2015',
      studyDegree: '12th, 85.80',
      isVisible: true,
    },
    {
      site: 'St. Joesphs Public School, Dalsinghsarai, Samastipur, Bihar',
      dateFrom: '2012',
      dateTo: '2013',
      studyDegree: '10th, 10 CGPA',
      isVisible: true,
    },
  ],
  certification: [
    {
      issuedBy: 'Finalist in Smart India Hackathon 2020 in Software Edition (Working as a leader of the project).',
      id: '',
      dateFrom: '',
      dateTo: '',
      isVisible: true,
    },
    {
      issuedBy: 'Secured 1st position in 12th class at STATE LEVEL.',
      id: '',
      dateFrom: '',
      dateTo: '',
      isVisible: true,
    },
  ],
  technicalSkills: [
    {
      category: 'Development Languages',
      keywords: [
        { name: 'JavaScript', level: 4 },
        { name: 'HTML', level: 4 },
        { name: 'CSS', level: 4 },
        { name: 'Bootstrap', level: 4 },
      ],
      isVisible: true,
    },
    {
      category: 'Technologies',
      keywords: [
        { name: 'MongoDB', level: 3 },
        { name: 'Express', level: 3 },
        { name: 'React', level: 4 },
        { name: 'Node.js', level: 4 },
        { name: 'Blockchain', level: 4 },
        { name: 'Java', level: 4 },
        { name: 'Python', level: 4 },
        { name: 'Redux', level: 2 },
        { name: 'Git', level: 4 },
        { name: 'GitHub', level: 4 },
        { name: 'Solidity', level: 4 },
        { name: 'C++', level: 3 },
      ],
      isVisible: true,
    },
  ],
  projects: [
    {
      name: 'BDmark: A Blockchain-based Solution to Big Data Watermarking',
      dateFrom: '05/2019',
      dateTo: '08/2019',
      link: 'https://github.com/vik625/Data_Chain_Management',
      teamBrief: 'IIT Patna',
      details: ['Software Technologies Used: Blockchain Technology, Solidity, Java, Truffle Suite, HTML, CSS, JavaScript', 'A novel approach that provides a transparent immutable audit trail for data movement in bigdata monetizing scenarios, by exploiting the power of both the watermarking and blockchain technologies.', 'We consider a complex big data monetization scenario where multiple actors are involved in data collection, aggregation, storage, selling, and purchasing.','We devise an access control mechanism which ensures that only legitimate buyers, with data-onwer’s permission, can get access to the target data-piece.'],
      isVisible: true,
    },
    {
      name: 'Management Information System for ministry of women & child development',
      link: 'https://github.com/vik625/AS33_RAM256KB',
      dateFrom: '08/2020',
      dateTo: '08/2020',
      teamBrief: 'Smart India Hackathon',
      details: ['A Decentralized App which contains all the necessary information about the loan-bound women entrepreneurs.', 'Features: The software mainly focuses on basic operations in a library like adding new members, new books, and updating new information, searching books and members, and facility to borrow and return books.', 'Role: Developer | Tools: Software engineering, Git, Django, Python, HTML, CSS, JavaScript, Jenkins.'],
      isVisible: true,
    },
    {
      name: 'Time-table Management System',
      link: 'https://github.com/vik625/AS33_RAM256KB',
      dateFrom: '01/2019',
      dateTo: '04/2019',
      teamBrief: 'IIITG',
      details: ['The software aims in developing a computerized system to maintain all the daily work of the library ', 'Features: The smart contract deployed in Blockchain are responsible to perform crucial functionalities, such as loan account info, repayment track record, personal info, SHG details, access policy, and the loan amount expenditure.', 'Role: Backend, blockchain, smart contract | Tools: HTML, CSS, Bootstrap, Web3.js, blockchain, solidity, ethereum'],
      isVisible: true,
    },
  ],
};

export default Resume;
